#:import Factory kivy.factory.Factory

<sp@SpinnerOption>:
	color: 1,0,0,1
	font_name: '1.ttf'
	background_color: 0.4, 0.4, 0, 1

<fscreen>
	canvas.before:
		Color:
			rgba: 1, 1, 1, 1
		Rectangle:
			size: root.width, root.height

	Spinner:
		id: drop
		size: root.width*0.4, root.height*0.05
		pos: root.width*0.3, root.height*0.5
		font_name: '1.ttf'
		text: 'DropDown'
		values: ['item 1', 'item 2', 'item 3', 'item 4']
		sync_height: True
		on_text: root.select()
		option_cls: Factory.sp
